### ISSUE TITLE
Mind adding a license?

### ISSUE THREAD

**Issue by bcantrill** [Blinningjr/rust-debug#1]
I know this seems absurd for a repo that's only a few hours old, but I hit upon this when looking for callers of `unwind_info_for_address` (I am a fellow consumer of Gimli!) and there's a bunch of helper code in here that's useful; would you mind adding a license to this?  With my thanks -- and apologies for the somewhat absurd request! ;)

**Comment by Blinningjr** [comment]
I have now added a license :)
